<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GameManager</AssemblyName>
    <RootNamespace>Bloxstrap.GameManager</RootNamespace>
    <Product>Microstrap Game Manager</Product>
    <Description>Browse, search and play Roblox games.</Description>
    <Version>0.1.0</Version>
    <ApplicationIcon>..\Bloxstrap\Microstrap.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\wpfui\src\Wpf.Ui\Wpf.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Bloxstrap\Microstrap.ico" Link="Microstrap.ico" />
  </ItemGroup>

</Project>
